name: 📦 Build Flatpak

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  flatpak:
    name: build-flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15-21.08
      options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build Flatpak
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle:  com.github.mkv-extractor-qt5.flatpak
          manifest-path: com.github.mkv-extractor-qt5.yml
          cache-key: flatpak-builder-${{ github.sha }}

