name: 📦 Build Flatpak

on:
  push:
    branches: [main]
  pull_request:

jobs:
  flatpak:
    name: build-flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15-22.08
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64]
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build Flatpak
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
        with:
          bundle: com.github.mkv-extractor-qt5.flatpak
          manifest-path: com.github.mkv-extractor-qt5.yml
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.arch }}
          branch: stable
      - name: Deploy
        if: github.event_name != 'pull_request'
        uses: flatpak/flatpak-github-actions/flat-manager@v4
        with:
          repository: ""
          flat-manager-url: https://flatpak.hachiman.nils.moe
          token: ${{ secrets.FLATMAN_TOKEN }}
